Stack:
  Default:
    Enabled: false
  Toggle:
    Enabled: true
  Tools:
    Enabled: false
  Armor:
    Enabled: false
Chest:
  Wand: 280
NoPermissions:
  OPOnly:
    C_All: false
    C_Top: false
    C_Range: false
    C_Chest: false
    C_Reload: true
    C_Stack: false
    Wand: false
# Users Automatically Added
Users:
  demonspork:
    Stack: true
    