name: InventorySort
main: Wolfwood.InventorySort.InventorySort
version: 0.9.2
author: Wolfwood
commands:
  sort:
    description:  Basic sort of your inventory.
    usage: |
           /<command> [top|all|0-35] [0-35]
  sortchest:
    description:  Sort the chest your looking at.
    usage: |
           /<command>