name: InventorySort
main: Wolfwood.InventorySort.InventorySort
version: 0.6
author: Wolfwood
commands:
  sort:
    description:  Basic sort of your inventory.
    usage: |
           /<command> [top|all|0-35] [0-35]