name: InventorySort
main: Wolfwood.InventorySort.InventorySort
version: 1.9.2
author: Wolfwood
commands:
  sort:
    description:  Sort of your inventory.
    usage: /<command> [top|all|0-35|stack|reload] [0-35]
  sortchest:
    description:  Sorts the chest your looking at.
    usage: /<command>
    aliases: ['srtc']