name: InventorySort
main: Wolfwood.InventorySort.InventorySort
version: 2.0
author: Wolfwood
commands:
  sort:
    description:  Sort of your inventory.
    usage: /<command> [top|all|0-35|stack|reload] [0-35]
  sortchest:
    description:  Sorts the chest your looking at.
    usage: /<command>
    aliases: ['srtc']
permissions:
  iSort.basic.all:
    description: Allows for the /sort all command.
    default: false
  iSort.basic.top:
    description: Allows for the /sort top command.
    default: false
  iSort.basic.range:
    description: Allows for /sort <0-35> <0-35> command.
    default: false
  iSort.basic.chest.command:
    description: Allows for the /sortchest and /srtc commands.
    default: false
  iSort.basic.chest.wand:
    description: Allows use of the wand to sort chests.
    default: false
  iSort.adv.stack:
    description: Allows the toggling automatic stacking using the /sort stack command.
    default: false
  iSort.adv.reload:
    description: Allows one to reload the config file with the /sort reload command
    default: op
  iSort.basic.*:
    description: All of the basic commands.
    children:
      iSort.basic.all: true
      iSort.basic.top: true
      iSort.basic.range: true
      iSort.basic.chest.command: true
      iSort.basic.chest.wand: true
  iSort.adv.*:
    description: All of the needed adv commands.
    children:
      iSort.adv.stack: true
  iSort.all:
    description: All of the needed commands.
    children:
      iSort.basic.all: true
      iSort.basic.top: true
      iSort.basic.range: true
      iSort.basic.chest.command: true
      iSort.basic.chest.wand: true
      iSort.adv.stack: true